language: elixir
elixir:
  - 1.7.4
otp_release:
  - 21.2
matrix:
  include:
  - otp_release: 18.0
    elixir: 1.3.0
sudo: false # to use faster container based build environment
cache:
  directories:
    - _build
    - deps
